name: Lint and Build
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: "Setup Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dist-${{ github.run_number }}
          path: dist